dist: xenial

env:
  global:
  - secure: smfuEjTcuFOVlI3WtWbM8E7Fy+iW/BREHeYfQY1fkcm7FNx1prpJKshPnLxxM/UA3/G+qyxFgBiS0mJkJCpyjloK+MaijUkOxr6qPY0MS2aEY4Ziku1IlBE2VuW7Sf2qbZAlJ6Rpa6flYILtcirVw/HmYfPMp7AgTrUrYwo+KRU3hJa93c0sj0H/f+norqreoAEOiwm9wui3eSJ/DTdW5BAyUwYX10bwl6JLVqDwuG2R+K/Oxpm6VI5h/sfC1GWa6Fi30yghgr0lzG4xt/iuMVTrFGWjRATzrZ48BXOHkRUjJrduJkGVCmmfsBmW/NiOhSUqntqp3Gtckjn4niNGyLU+cqCYf7G9SCAFVxXXTeciqIqIYUjZMpi5AZ1id8lHI0jbNHtAwR+36s+NEyl/6Om7y7OY/Sg53SJ1OE06dbSMajFIDjlX/ExYF+AUT/3CO3i6Bi9oF8txPNJbdx7l5VYmQYEP3jEThq3e84YiofdPrNMCpNrzopSx3a+z/jkouBNaPFk6bkvFXdqJ1498/fB6J4cWLbvKDAy6xxt9ahywsBVbgpwBwyr/X8Xblgr74sLCIk/1gNHDyUWKyhXJ0VvIkS/1sx2Z1XWvIqqc+7RCHAIvH2hoDEXBlbde7Qeivs7fdZScxi0qMvodbDEF45A//kzumPJK/UVuOdyg/go=
  - secure: Pe2Jv4okjiovne3DrAV4FZfiZmX+XDY0UrkRYYQsz65KriXzll8AyIRs7ZYTyqbGrCH5dc7WJQEKHdRQ4jUtC/5cyngaiga4Et++wGwp04AkAX1AykbKyDHzBGsfW4oKOA7kfsFYG6mk30murVEi7wDo1B4vb6HbW6hwOHhsK0/i9y69q++ITSatnsJV1v3WJZWMJ+i/ExMwamybGXnSHfZQBl7DL+3CNdbOlebrDGxVHblD4qz8uWcbMNftgCCCjb2Skt3xXA6RROY5UXn4QMDZjvLBHI2tnyZqg95aBjzq9Rjfa6havCwkWsKmKrnRNGBfWGjEQh4p1MkgTzPah1G5NUOx7iK/AlpRqwteoaCjUVkEH1dK4vNuYXpPacred6rIQHM+KbL28s5fJWgltgKK5hnAPlJzTW7VhnN2yUuUZiG2gsm3J0+kmIcpSc8EIb6/F9PtMIZzjoBb/1BcrnzFT1RfMaY+om+EB75zqlujIbD+aKvHOq7Li9INrm5YDhkPjxddwsgOOJrdTYbEtLjud2sh2oHAR6mldKStbemrW99spw4c7lAM96zFuQ+bkEfB4Bk0NkYjFadLFUr8KuGpFTsnEQeFNX62fPV3K/2Vdx7y8gGNsM3v48A0FKIn+WLlxWAAGwgmjwE4n9nnvACtj7i1nuMVD8X239rpPwI=
  - DOCKER_COMPOSE_VERSION=1.23.2

language: generic

services:
- docker

before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

script:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- export ${AWS_ACCESS_KEY_ID}
- export ${AWS_SECRET_ACCESS_KEY}
- eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
- docker pull 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild
- docker build -f Mirza.Dockerfile --tag --target BUILD -t 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild --cache-from 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild:latest .
- eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
- docker push 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild:latest
- docker build -f Mirza.Dockerfile --target PKG-SCS -t 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/supplychainserver:$TRAVIS_COMMIT .
- docker build -f Mirza.Dockerfile --target PKG-BR -t 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/businessregistry:$TRAVIS_COMMIT .
- docker push 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/supplychainserver:$TRAVIS_COMMIT
- docker push 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/businessregistry:$TRAVIS_COMMIT
