dist: xenial
env:
  global:
  - secure: mx34e7ZMoGhJlobOvY8mUMIISC3dDUBDSYcb9s6BFKD5gDC1qT2nz0whmWcCQh5XlAzVcLHcEmzAWhpDoBLecRPzq+pHTJg8WwmZEpQt8NLJMvvtQwcYLls8lm3samfQUjsqY4MB4qzb2YedY7052AI7VseKxpwop2GnqM3x1FcCmYQ2DKLNiomUH2F+GpZz30VGhJKwu7RblZAES8aIr00jQ4KcuhhsWnGLf7s5B2oDa3S56HhyPvEUIeS75APu4XYxSVLhF6aNm6qgQjudAXbjAzV6YRNOAFVf/7IL6dsPVwwnPF4Nrxio76eLXE0u7ey4PK+akacxTUYAY9HP0M9TAmH+Cq3pSnDAwqZFBBXQfCZz2jC8IS9UBTIUYQU2Uo9H2hVD0zYI5OCTnsiuH1xsj1arZwSs3USanyzm6InrDUdQGx17iiwz9t3dnbEJk/aM1trCHKOEAta9Il4so3KaVtK/0GPVIC1JATYkNkgiqj1UK1lFqolGhLr/vP+jgMF9HmlzT1RGuEPPni3Upk3QMQZBIoC3r+kxAnlGJ54wgUCYjeNMoTsLK9Cf9vaZhhpDPjuOhiFlGKEVdw2vVjQ4ZDyk0RSK0uBrOY6R3RnrO+AOmAhYO7fWGvjRR5yNIR9UFJbg3mIZ3T3jauMjuPPplfbqGzS13gFkzbxMcbk=
  - secure: k9mPDnNDPA2LKE+u+Z8hDNAdRxD0WiOqbxHRKArX7TuQZRUhznvtMcMYtSv5aF2iL8c8M9814Et2mXoJOage/Wcup8WVZeA403cS7qogt3/gJLZ8Tz1ZkOyt8d7fs6xAYIowqM0qzoqRJ8V9TcjFVmJ3p3hZjzbl/meHF4hsnHYYP2XLzAKyBqepTjCIriD/zOk+P4uF1U7XwCVwfqNdsRjw8VmI/uEZyYX1ekscxf4AJM67kDmYeojcPf/R8h6ufEcTExL7tweQZ6ypXQVjCGJIalb1NsPhfRFJ9f/8Ti4r3Gsq/2KO4JKKW8pu5sf1rx3QZD5jxK57BDXd/cqV94ejU4mBo9cYHxQZ73A2aqMa0PkXBuAF24DpFoRkvamb9aDk30qOxrTmMSZ8Oee1KUlYhtsOtt3Qhm7qjvS6PUoTYJJqKXLK0VsjCyynt20RUH+6p94uNEgrETxDCIVYzS4Eethx1N6GqxKKs1V8cKopwC3C+kJLsYCtVBR/sDxS1IcbnJ7nojNDFr6O6ize5vH7arUiuBmD23ojPIXqL/VFew4RFlD9FsObrVQOqXRneIDOCxNuLBr5+Vsg3/UkMQqZVvUtENszvpPAr5mac92vLLCcwZZoUai7Zj17XZtDi83wyJoHgQboBJbDAv69TQZFZXTNKUhSHiua1ZsYcNo=
  - DOCKER_COMPOSE_VERSION=1.23.2

language: generic

services:
- docker

before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

script:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
- docker pull 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild
- docker build -f Mirza.Dockerfile --target BUILD -t 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild --cache-from 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild:latest  .
- eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
- docker push 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild:latest
- docker build -f Mirza.Dockerfile --target PKG-SCS -t 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/supplychainserver:$TRAVIS_COMMIT --cache-from 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild:latest .
- docker build -f Mirza.Dockerfile --target PKG-BR -t 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/businessregistry:$TRAVIS_COMMIT --cache-from 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/mirzabuild:latest .
- docker push 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/supplychainserver:$TRAVIS_COMMIT
- docker push 235945186688.dkr.ecr.ap-southeast-2.amazonaws.com/businessregistry:$TRAVIS_COMMIT
