flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/tathougies/beam.git
    commit: b15f69865d5025d64df863f0890eb681f28f9ae3
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: git@github.csiro.au:Blockchain/GS1Combinators.git
  commit: e3a43759f211289197d46c7d4cd7b523d9d66b3f
- servant-0.10
- servant-multipart-0.10
- servant-server-0.10
- servant-swagger-1.1.2.1
resolver: lts-9.0
