flags: {}
extra-package-dbs: []
packages:
- '.'
- ../GS1Combinators
- location:
    git: https://github.com/tathougies/beam.git
    commit: a3b5e0763843fed48c7eef53fa7d08cfe710342d
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
    # - beam-sqlite
extra-deps:
- aeson-1.1.2.0
- cpphs-1.20.8
- directory-1.2.7.1
- servant-0.10
- servant-server-0.10
- servant-swagger-1.1.2.1
- vector-0.12.0.1
- storable-tuple-0.0.3.3
resolver: lts-8.6
# subdirs:
#     - beam-core
#     - beam-migrate
#     - postgres