extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/tathougies/beam.git
    commit: 01bbb89c03b93daa2500877a511159df9d91002a # Head on 2018-07-02
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: git@github.csiro.au:Blockchain/GS1Combinators.git
  commit: a96c9fc1c14ddf7ef69756d7504feca9ff667c65
- Unique-0.4.7.5@sha256:580b578ddde452111cc20aa84bdccd7e723d19eb4f8d167d2358d08a4637eed3
- servant-flatten-0.2
- hspec-2.5.0
- hspec-core-2.5.0
- hspec-discover-2.5.0
- katip-0.5.5.0
- hoist-error-0.2.1.0

resolver: lts-12.0
# allow-newer: true
ghc-options:
  $locals: -Wall

nix:
  packages: [zlib]
