flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/tathougies/beam.git
    commit: 3553ba7edcc3b85749530262fc12af6584061fa2
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: git@github.csiro.au:Blockchain/GS1Combinators.git
  commit: 0514a70af90b7d8317eadc8a579734cda235f84e
- servant-0.10
- servant-multipart-0.10
- servant-server-0.10
- servant-swagger-1.1.2.1
- vector-0.12.0.1
- storable-tuple-0.0.3.3
resolver: lts-9.21
# allow-newer: true
