flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/sajidanower23/beam.git
    # git: https://github.com/tathougies/beam.git
    commit: e934ad375c327a75ffbd6c1698f44a80157fc706
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: git@github.csiro.au:Blockchain/GS1Combinators.git
  commit: dc2af23ff4dce8139afa947258f6354c2c1458b1
- servant-0.10
- servant-multipart-0.10
- servant-server-0.10
- servant-swagger-1.1.2.1
- vector-0.12.0.1
- storable-tuple-0.0.3.3
#- RSA-1.0.3
# - beam-migrate-0.2.0.0
resolver: lts-9.21
# allow-newer: true
