extra-package-dbs: []
packages:
- '.'
- location:
    # git: https://github.com/sajidanower23/beam.git
    git: https://github.com/tathougies/beam.git
    commit: ba7c05a743d1924588a436d34c741a949adb2cdd
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
- location:
    git: https://github.com/qfpl/hs-hoist-error.git
    commit: f1f7b181bcd6969a2f502823d329dc4f050b9a9e
  extra-dep: true
extra-deps:
- git: git@github.csiro.au:Blockchain/GS1Combinators.git
  commit: 2203815854b7e832e976bcf90d66529feec0584e
- servant-flatten-0.2

resolver: lts-11.6
# allow-newer: true
