extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/tathougies/beam.git
    commit: 2489a213cdee6341de46a3aa015c35067f4d6076 # Head on 2019-01-10
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: https://github.com/data61/GS1Combinators.git
  commit: 0b41a51a746616350cceef6ca91ee5869340dd12
- git: https://github.com/kapralVV/Unique.git
  commit: 8b543fd9c9f9e3909875942098a47df19a68c9da  # Head on 2019-01-10
- servant-flatten-0.2
- hoist-error-0.2.1.0

resolver: lts-13.2
# allow-newer: true
ghc-options:
  $locals: -Wall

local-bin-path: dist

nix:
  packages: [zlib]
