flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    # git: https://github.com/sajidanower23/beam.git
    git: https://github.com/tathougies/beam.git
    commit: 03f1091b0e0e05a76ec622e454e0c95a7195fb25
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: git@github.csiro.au:Blockchain/GS1Combinators.git
  commit: 56a1fc9e325af73c414e9834f971da9837700f33
- servant-0.11
- servant-multipart-0.10
- servant-server-0.11
- swagger2-2.1.6
- vector-0.12.0.1
- storable-tuple-0.0.3.3

resolver: lts-10.6
# allow-newer: true
