flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    # git: https://github.com/sajidanower23/beam.git
    git: https://github.com/tathougies/beam.git
    commit: 1673f0762f9beca04923518bca1ba5c519fd56a3
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: git@github.csiro.au:Blockchain/GS1Combinators.git
  commit: d0867901afb32c14af69bef6735b29ee476112e2
- servant-0.11
- servant-multipart-0.10
- servant-server-0.11
- swagger2-2.1.6

- vector-0.12.0.1
- storable-tuple-0.0.3.3
#- RSA-1.0.3
# - beam-migrate-0.2.0.0

resolver: lts-10.6
# allow-newer: true
