extra-package-dbs: []
packages:
- '.'
- '../mirza-common-haskell'
- location:
    git: https://github.com/tathougies/beam.git
    commit: a89da5ba70f1e10b907097548a02ff6dd08e192d # Head on 2019-03-25
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: https://github.com/sajidanower23/hs-jose.git
  commit: d7aca4d13b27235af47d522b5d093e567750628e
- git: https://github.com/data61/GS1Combinators.git
  commit: 3c4bbe4c1fbb2d25c988c99cfbfc3cf0bcf1fe02 # Head on 2019-06-06
- servant-flatten-0.2
- hoist-error-0.2.1.0

resolver: lts-13.23

ghc-options:
  $locals: -Wall

local-bin-path: dist

nix:
  packages: [zlib]
