extra-package-dbs: []
packages:
- '.'
- '../mirza-common-haskell'
extra-deps:
- git: https://github.com/tathougies/beam.git
  commit: 737b73c6ec1c6aac6386bf9592a02a91f34a9478 # Head on 2019-03-19
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
- git: https://github.com/sajidanower23/hs-jose.git
  commit: d7aca4d13b27235af47d522b5d093e567750628e
- git: https://github.com/data61/GS1Combinators.git
  commit: 7f0f0c9c2ec6d91378ac56ba63de033fcc313326 # Head on 2019-06-14
- servant-flatten-0.2
- hoist-error-0.2.1.0

resolver: lts-13.23

ghc-options:
  $locals: -Wall

local-bin-path: dist

nix:
  packages: [zlib]
