extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/tathougies/beam.git
    commit: 2489a213cdee6341de46a3aa015c35067f4d6076 # Head on 2019-01-10
  extra-dep: true
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
extra-deps:
- git: https://github.com/sajidanower23/hs-jose.git
  commit: d7aca4d13b27235af47d522b5d093e567750628e
- git: https://github.com/data61/GS1Combinators.git
  commit: 6e3eac1448d55dcc934e22cc665a92aa97c1eb9d # Head on 2019-05-29
- servant-flatten-0.2
- hoist-error-0.2.1.0

resolver: lts-13.23

ghc-options:
  $locals: -Wall

local-bin-path: dist

nix:
  packages: [zlib]
