extra-package-dbs: []
packages:
- '.'
- '../mirza-common-haskell'
- '../mirza-test-utils-haskell'
extra-deps:
- git: https://github.com/tathougies/beam.git
  commit: 737b73c6ec1c6aac6386bf9592a02a91f34a9478 # Head on 2019-03-19
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
- git: https://github.com/sajidanower23/hs-jose.git
  commit: d7aca4d13b27235af47d522b5d093e567750628e
- git: https://github.com/data61/GS1Combinators.git
  commit: ddb92e443055e7719fa46afa5913cf2276cfd71e # Head on 2019-08-13
- servant-flatten-0.2
- hoist-error-0.2.1.0

resolver: lts-13.23

ghc-options:
  $locals: -Wall

local-bin-path: dist

nix:
  packages: [zlib]
