packages:
- '.'
- ../mirza-common-haskell

extra-deps:
- git: https://github.com/tathougies/beam.git
  commit: 2489a213cdee6341de46a3aa015c35067f4d6076 # Head on 2019-01-10
  subdirs:
    - beam-core
    - beam-migrate
    - beam-postgres
- git: https://github.com/data61/GS1Combinators.git
  commit: 7f0f0c9c2ec6d91378ac56ba63de033fcc313326 # Head on 2019-06-14

resolver: lts-13.23
ghc-options:
  $locals: -Wall

local-bin-path: dist
