CREATE TABLE IF NOT EXISTS SupplyChain.Users (id INTEGER PRIMARY KEY AUTOINCREMENT, bizID INTEGER, firstName TEXT NOT NULL, lastName TEXT);

CREATE TABLE IF NOT EXISTS SupplyChain.Keys (id INTEGER PRIMARY KEY AUTOINCREMENT, userID INTEGER, publicKey BLOB, timeCreated INTEGER, revocationTime INTEGER DEFAULT NULL);

CREATE TABLE IF NOT EXISTS SupplyChain.Business (id INTEGER PRIMARY KEY AUTOINCREMENT, businessName TEXT NOT NULL, location TEXT, businessFunction TEXT);

CREATE TABLE IF NOT EXISTS SupplyChain.Contacts (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER NOT NULL, user2 INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS SupplyChain.Contact (id INTEGER PRIMARY KEY AUTOINCREMENT, user1 INTEGER NOT NULL, user2 INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS SupplyChain.Signatures (id INTEGER PRIMARY KEY AUTOINCREMENT, userID INTEGER NOT NULL, keyID INTEGER NOT NULL, timestamp INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS SupplyChain.Hashes (id INTEGER PRIMARY KEY AUTOINCREMENT, signedEventID INTEGER NOT NULL, hashID INTEGER NOT NULL, hash BLOB NOT NULL);

CREATE TABLE IF NOT EXISTS SupplyChain.Events (id INTEGER PRIMARY KEY AUTOINCREMENT, what TEXT, why TEXT, location TEXT, when TEXT, eventType INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS SupplyChain.EventTypes (id INTEGER PRIMARY KEY AUTOINCREMENT, eventType TEXT NOT NULL);

